# coding: utf-8
"""
Django settings for ResumeAnalysis project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(tts#1%t&57g820e#-rk6jp5z7^8q0wv_ies4z-)_!h15r$@az'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

import pymongo


class MongoConf:
    """mongodb 配置文件"""
    # 简历库mongo配置
    resume_host = "171.221.173.155"
    resume_port = 27017
    resume_db = "xunying_resume"
    resume_table = "resume_4_1_v3"
    resume_user = "admin"
    resume_password = "abc@123"

    # 维度库mongo配置
    dimension_host = "171.221.173.155"
    dimension_port = 27017
    dimension_db = "dimension"
    dimension_table = "dimension"
    dimension_user = "admin"
    dimension_password = "abc@123"

    # 授权简历库
    resume_mongo = pymongo.Connection(resume_host, resume_port)
    resume_mongo["admin"].authenticate(resume_user, resume_password)
    resume_mongo.safe = True
    resume_collection = resume_mongo[resume_db][resume_table]

    # 授权维度库
    dimension_mongo = pymongo.Connection(dimension_host, dimension_port)
    dimension_mongo["admin"].authenticate(dimension_user, dimension_password)
    dimension_mongo.safe = True
    dimension_collection = dimension_mongo[dimension_db][dimension_table]
